name: locationReminder
version: '1.0-SNAPSHOT'
main: me.aujung.locationReminder.LocationReminder
api-version: '1.21'
commands:
  postLocation:
    description: locationReminder command
    usage: /postLocation <locationName>
    aliases: [ploc]
  listLocation:
    description: locationReminder command
    usage: /listLocation
    aliases: [ll]
  deleteLocation:
    description: locationReminder command
    usage: /deleteLocation
    aliases: [dl]
  broadcastLocation:
    description: locationReminder command
    usage: /broadcastLocation
    aliases: [bl]
