name: locationReminder
version: '1.0-SNAPSHOT'
main: me.aujung.locationReminder.LocationReminder
api-version: '1.21'
commands:
  postLocation:
    description: locationReminder command
    usage: /postLocation <locationName>
    aliases: [pl]
  listLocation:
    description: locationReminder command
    usage: /listLocation
    aliases: [ll]
  deleteLocaiton:
    description: locationReminder command
    usage: /deleteLocation
    aliases: [dl]
